### ISSUE TITLE
Refactoring, alles in .lua Dateien auslagern

### ISSUE THREAD

**Issue by Kebap** [Kebap/krrrcks-mudlet#29]
Entwickler haben Unmut geäußert, alles in Mudlet zu schreiben. Zudem ist der XML-Export nur schwer direkt lesbar/änderbar, da Sonderzeichen in HMTL-Codes umgewandelt werden.

Ziel soll sein, im XML nur ganz wenige Kommandos zu behalten. Diese sorgen dafür, dass die eigentlichen Inhalte (Trigger, Alias, Scripte, usw.) aus eigenständigen Dateien (bspw. trigger.lua, alias.lua, scripte) oder erweiterbaren Komponenten (bspw. kaempfer.lua, usw.) nachgeladen werden.

Als Orientierungspunkt kann Vyzor fungieren, wobei dort keine Trigger, usw. benutzt werden, sondern sogar komplette Logiken aus eigenen .lua Dateien nachgeladen werden.

**Comment by krrrcks** [comment]
Ja, das hat mich damals auch ziemlich abgeschreckt, diese XML-Geschichte. Wenn man das schön in Lua-Dateien bekäme, wäre das glaube ich für die Weiterentwicklung am besten.

**Comment by Kebap** [comment]
== Benötigte Teile für Inhalte des Mudlet Paketes derzeit:

Triggers
* Gruppen von Einträgen
* pro Eintrag: name, matchline, matchtype (exact, regex, substring,.), trigger content, fire length, highlight, fg color, bg color, 

Aliases
* Gruppen von Einträgen
* pro Eintrag: Alias name, Pattern (type: Regex wohl fast immer), Substitution, Script content, 

Timers
* noch nix

Scripts
* Gruppen von Einträgen
* pro Eintrag: Script Name, Script contents, Registered Event Handlers (zB gmcp.MG.room.info in Script handleRoomInfo)

Action Key Bindings
* Gruppen von Einträgen
* pro Eintrag: Name, Command, Key Binding



== Befehle, um die Sachen direkt aus .lua Dateien zu erstellen:


Triggers
* permRegexTrigger
* Manual: http://wiki.mudlet.org/w/Manual:Technical_Manual#permRegexTrigger

* permSubstringTrigger
* Manual: http://wiki.mudlet.org/w/Manual:Technical_Manual#permSubstringTrigger

* Gilt diese Trennung so weiterhin? Ich habe auch Trigger mit gemischten Patterns. 2 Regex & 3 Substring.


Alias prüfen und erstellen
* permAlias
* Manual: http://wiki.mudlet.org/w/Manual:Technical_Manual#permAlias
* Beispiel:
if exists("Vyzor Help", "alias") == 0 then
  permAlias("Vyzor Help", "vyzor", [[^vy(?:zor)?\s?h(?:elp)?$]], [[   alias content   ]])
end


Scripts
* ? nicht gefunden, existiert Befehl überhaupt?


Action Key Bindings
* permKey(name, parent, modifier, key code, lua code)
* Manual: http://wiki.mudlet.org/w/Manual:Technical_Manual#permKey
* Beispiel:
-- create a key at the top level for F8 
permKey("my key", "", mudlet.key.F8, echo("hey this thing actually works!\n"))


Sonstiges: Existenz / Häufigkeit prüfen
* exists(name, type) 
* Manual: http://mudlet.sourceforge.net/wordpress/wp-content/uploads/2013/02/mudlet_api_reference_html.html#exists
* Beispiel: siehe permGroup

Sonstiges: Gruppe erstellen (und vorher prüfen)
* permGroup(name, itemtype)
* Manual: http://wiki.mudlet.org/w/Manual:Technical_Manual#permGroup
* Beispiel:
if exists("vyzor", "alias") == 0 then
  permGroup("vyzor", "alias")
end
* Erstellt nur Gruppen auf Hauptebene (Root) und nicht darunter ?!

**Comment by Kebap** [comment]
* Trigger mit mehreren Patterns: tempComplexRegexTrigger() - aber nicht permanent. Oder mehrere Trigger nebeneinander in einen Ordner räumen?

* Scripts lassen sich anscheinend gar nicht per Befehl erstellen. Bedarf scheint noch nicht dagewesen. Vorschlag ist, diese in Trigger, etc. zu verschieben. 

* Trigger lassen sich dann auch per Event auslösen, was wir heute bei Scripts auf anderem Weg erreichen: http://wiki.mudlet.org/w/Manual:Event_Engine#Registering_an_event_from_a_script

* Beide Vorschläge haben den Nachteil, dass komplexe Trigger und Events anonym wären, also für den User in der GUI unsichtbar. Daher sollte Mudlet Änderung angefragt werden

**Comment by Kebap** [comment]
Problem ist zudem, dass diese Mudlet Befehle den Lua Code dann als String erwarten. Man kann String nicht so schön handhaben, analysieren und erweitern wie echte Funktionen. Scheint aber dennoch weit sinnvoller als das derzeitige Vorgehen über XML-Codierung, usw.

Anscheinend kann man die Strings anschließend doch noch in echte Funktionen umwandeln:
https://www.lua.org/manual/5.3/manual.html#pdf-load

**Comment by Kebap** [comment]
* Sammlung der tatsächlichen Übersetzungen hier: https://github.com/Kebap/krrrcks-mudlet/wiki/Refactory
* Rücksprache mit Mudlet Community zwecks Vorgehen trotz fehlender Funktionalitäten hier: https://forums.mudlet.org/viewtopic.php?f=9&t=4611

**Comment by Kebap** [comment]
Grundsätzliche Entscheidung offen:

* Sollen Scripte schön alle in Lua-Dateien wohnen, so dass man sie dort bequem bearbeiten kann? Nachteil: Sie sind in Mudlet unsichtbar. Aktualisieren der Lua-Dateien wirkt sich nicht sofort auf Mudlet aus.
* Oder sollen Scripte in Mudlet sichtbar sein, so dass man sie auch dort bequem weiter bearbeiten kann? Nachteil: Umständlicher zu realisieren; in Lua nicht mehr so schön; nur teilweise Unterstützung durch Mudlet-Core

Ich bin eigentlich für die zweite Lösung, aber erwäge nun auch ersteres.
Es ist nur eine grundsätzliche Entscheidung, die sich dann nicht so leicht revidieren lässt.
Habe von einigen Spielern gehört, dass dieses Paket ihnen geholfen hat, eigene Sachen in Mudlet zusammenzuklicken. Unklar, ob sie dazu in Lua-Dateien rumfummeln würden, wenn sie in Mudlet nichts sehen.

**Comment by Kebap** [comment]
Beste aus zwei Welten vielleicht: [Muddler](https://forums.mudlet.org/viewtopic.php?f=7&t=22765)
Entwickeln in Lua-Dateien, daraus automatisch (per Java) ein Mudlet Paket erstellen lassen, das bei den Spielern dann die GUI-Elemente installiert, als wären sie direkt in Mudlet entwickelt worden,
Einziger Nachteil: Falls die GUI-Elemente dort weiter bearbeitet werden, gibt es noch keine automatische Möglichkeit, um die Lua-Dateien entsprechend anzupassen. Entwickler müssten Änderungen manuell überführen.

**Comment by Kebap** [comment]
@krrrcks schrieb:
> Ja, das hat mich damals auch ziemlich abgeschreckt, diese XML-Geschichte. Wenn man das schön in Lua-Dateien bekäme, wäre das glaube ich für die Weiterentwicklung am besten.

Dieser Wunsch wurde in den letzten Tagen erfolgreich umgesetzt. Siehe https://github.com/MorgenGrauen/mg-mudlet
